-- MySQL Script generated by MySQL Workbench
-- Di 07 Okt 2014 12:19:48 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Table `ad_discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ad_discount` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `occupancy` INT NULL,
  `year` CHAR(1) NULL,
  `discount` DECIMAL(10,2) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NULL,
  `format` VARCHAR(45) NULL,
  `date` DATETIME NULL,
  `height` INT NULL,
  `width` INT NULL,
  `blend` INT NULL,
  `describtion` TEXT NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `ad_discount_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Ad_ad_discount1_idx` (`ad_discount_id` ASC),
  CONSTRAINT `fk_Ad_ad_discount1`
    FOREIGN KEY (`ad_discount_id`)
    REFERENCES `ad_discount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `active` TINYINT(1) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `street` VARCHAR(255) NULL,
  `house_number` VARCHAR(255) NULL,
  `postal_code` INT(5) NULL,
  `place_of_residence` VARCHAR(255) NULL,
  `post_of_residence` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `customer_id` INT NOT NULL,
  `address_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_address_customer1_idx` (`customer_id` ASC),
  INDEX `fk_address_address_type1_idx` (`address_type_id` ASC),
  CONSTRAINT `fk_address_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address_address_type1`
    FOREIGN KEY (`address_type_id`)
    REFERENCES `address_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NULL,
  `deadline` DATETIME NULL,
  `price` DECIMAL(10,2) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `customer_id` INT NOT NULL,
  `successful` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_offer_customer1_idx` (`customer_id` ASC),
  CONSTRAINT `fk_offer_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `deadline` DATE NULL,
  `price` DECIMAL(10,2) NULL,
  `position` INT NULL,
  `active` TINYINT(1) NULL,
  `booking` TINYINT(1) NULL,
  `work_order` TINYINT(1) NULL,
  `finish` TINYINT(1) NULL,
  `cancellation` TINYINT(1) NULL,
  `invoice` TINYINT(1) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `customer_id` INT NOT NULL,
  `offer_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_order_customer1_idx` (`customer_id` ASC),
  INDEX `fk_order_offer1_idx` (`offer_id` ASC),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_offer1`
    FOREIGN KEY (`offer_id`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `order_position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `describtion` TEXT NULL,
  `single_price` DECIMAL(10,2) NULL,
  `amount` INT NULL,
  `total_price` DECIMAL(10,2) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `Ad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_order_position_order1_idx` (`order_id` ASC),
  INDEX `fk_order_position_Ad1_idx` (`Ad_id` ASC),
  CONSTRAINT `fk_order_position_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_position_Ad1`
    FOREIGN KEY (`Ad_id`)
    REFERENCES `ad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `exhortation` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_invoice_order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_invoice_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offer_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offer_position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `describtion` TEXT NULL,
  `single_price` DECIMAL(10,2) NULL,
  `amount` INT NULL,
  `total_price` DECIMAL(10,2) NULL,
  `created` DATETIME NULL,
  `created_by` INT NULL,
  `modified` DATETIME NULL,
  `modified_by` INT NULL,
  `offer_id` INT NOT NULL,
  `Ad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `offer_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_offer_position_offer1_idx` (`offer_id` ASC),
  INDEX `fk_offer_position_Ad1_idx` (`Ad_id` ASC),
  CONSTRAINT `fk_offer_position_offer1`
    FOREIGN KEY (`offer_id`)
    REFERENCES `offer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_offer_position_Ad1`
    FOREIGN KEY (`Ad_id`)
    REFERENCES `ad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
